#!/usr/bin/dh-exec
[arm64] lib/modules/6.12.92-cip25-ls64-slingshot/sshot/sl.ko   opt/hpe/r2/lib/modules/6.12.92-cip25-ls64-slingshot/sshot
[amd64] lib/modules/6.12.92-cip25-amd64-slingshot/sshot/sl.ko  opt/hpe/r2/lib/modules/6.12.92-cip25-amd64-slingshot/sshot
lib/firmware/sl_fw_quad_3.04.bin  opt/hpe/r2/lib/firmware/
lib/firmware/sl_fw_octet_3.08.bin opt/hpe/r2/lib/firmware/
lib/firmware/sl_cable_db.bin      opt/hpe/r2/lib/firmware/
usr/bin/slstat
