/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright 2025 Hewlett Packard Enterprise Development LP */

#ifndef _SL_CORE_HW_SERDES_OSPREY_H_
#define _SL_CORE_HW_SERDES_OSPREY_H_

#include "hw/sl_core_hw_serdes_addrs.h"

u16 serdes_addrs_osprey[] = {
	[SERDES_DIG_COM_B_LANE_ADDR_0]                                         = 0xD190,
	[SERDES_MICRO_B_COM_RMI_MICRO_SDK_STATUS0]                             = 0xD21A,
	[SERDES_DIG_COM_REVID0]                                                = 0xD100,
	[SERDES_DIG_COM_REVID1]                                                = 0xD10A,
	[SERDES_DIG_COM_REVID2]                                                = 0xD10E,
	[SERDES_HW_VERSION]                                                    = 0xD0D8,
	[SERDES_MICRO_E_COM_MICRO_CORE_CLOCK_CONTROL0]                         = 0xD240,
	[SERDES_MICRO_E_COM_MICRO_CORE_RESET_CONTROL0]                         = 0xD241,
	[SERDES_MICRO_C_COM_RAM_CONTROL0]                                      = 0xD227,
	[SERDES_MICRO_A_COM_CLOCK_CONTROL0]                                    = 0xD200,
	[SERDES_MICRO_A_COM_RESET_CONTROL0]                                    = 0xD201,
	[SERDES_MICRO_A_COM_AHB_CONTROL0]                                      = 0xD202,
	[SERDES_MICRO_A_COM_AHB_STATUS0]                                       = 0xD203,
	[SERDES_MICRO_B_COM_RMI_RAM_CR_CRCCONTROL0]                            = 0xD217,
	[SERDES_MICRO_B_COM_RMI_RAM_CR_CRCSTATUS0]                             = 0xD218,
	[SERDES_MICRO_A_COM_PRAMIF_CONTROL0]                                   = 0xD20C,
	[SERDES_MICRO_A_COM_PRAMIF_AHB_WRADDR_LSW]                             = 0xD20D,
	[SERDES_MICRO_A_COM_PRAMIF_AHB_WRADDR_MSW]                             = 0xD20E,
	[SERDES_MICRO_D_COM_RMI_MICRO_CONTROL0]                                = 0xD23E,
	[SERDES_MICRO_C_COM_RAM_CONTROL2]                                      = 0xD22E,
	[SERDES_COMMON_CLOCK]                                                  = 0xD19D,
	[SERDES_MDIO_MMDSEL_AER_COM_MDIO_BRCST_PORT_ADDR]                      = 0xFFDC,
	[SERDES_RXTXCOM_CKRST_CTRL_RXTXCOM_LANE_CLK_RESET_N_POWERDOWN_CONTROL] = 0xD0B1,
	[SERDES_CORE_PLL_COM_TOP_USER_CONTROL]                                 = 0xD184,
	[SERDES_DIG_COM_RESET_CONTROL_PMD]                                     = 0xD101,
	[SERDES_CORE_PLL_COM_RESET_CONTROL_PLL_DP]                             = 0xD182,
	[SERDES_PLL_RESET2]                                                    = 0xD119,
	[SERDES_AMS_PLL_COM_PLL_CONTROL_10]                                    = 0xD11A,
	[SERDES_AMS_PLL_COM_PLL_CONTROL_11]                                    = 0xD11B,
	[SERDES_AMS_PLL_COM_PLL_CONTROL_12]                                    = 0xD11C,
	[SERDES_PLL_CAL_COM_STS_0]                                             = 0xD148,
	[SERDES_TXCOM_CKRST_CTRL_TXCOM_LANE_CLK_RESET_N_POWERDOWN_CONTROL]     = 0xD1D1,
	[SERDES_TXCOM_CKRST_CTRL_TXCOM_LN_S_RSTB_CONTROL]                      = 0xD1DE,
	[SERDES_RXCOM_LANE_CLK_RESET_N_POWERDOWN_CONTROL]                      = 0xD1C1,
	[SERDES_RXCOM_CKRST_CTRL_RXCOM_LN_S_RSTB_CONTROL]                      = 0xD1CE,
	[SERDES_PLL_COM_PLL_CONTROL_2]                                         = 0xD112,
	[SERDES_PLL_COM_PLL_CONTROL_1]                                         = 0xD111,
	[SERDES_PLL_COM_PLL_CONTROL_4]                                         = 0xD114,
	[SERDES_PLL_POWER_DOWN]                                                = 0xD327,
	[SERDES_PLL_COM_B_PLL_CTRL_0]                                          = 0xD320,
	[SERDES_PLL_COM_B_PLL_CTRL_2]                                          = 0xD322,
	[SERDES_PLL_COM_B_PLL_CTRL_1]                                          = 0xD321,
	[SERDES_PLL_CONTROL]                                                   = 0xD110,
	[SERDES_PLL_COM_PLL_CONTROL_3]                                         = 0xD113,
	[SERDES_PLL_COM_B_PLL_CTRL_3]                                          = 0xD323,
	[SERDES_PLL_SELECT]                                                    = 0xD11D,
	[SERDES_PLL_FW_API_DATA0]                                              = 0xD18D,
	[SERDES_TX_FED_TXFIR_TAP_CONTROL0]                                     = 0xD133,
	[SERDES_TX_FED_TXFIR_TAP_CONTROL1]                                     = 0xD134,
	[SERDES_TX_FED_TXFIR_TAP_CONTROL2]                                     = 0xD135,
	[SERDES_TX_FED_TXFIR_TAP_CONTROL3]                                     = 0xD136,
	[SERDES_TX_FED_TXFIR_TAP_CONTROL4]                                     = 0xD137,
	[SERDES_TX_FED_TXFIR_TAP_CONTROL5]                                     = 0xD138,
	[SERDES_CDR_CONTROL_0]                                                 = 0xD590,
	[SERDES_FW_API_DATA0]                                                  = 0xD1AD,
	[SERDES_AMS_TX_TXCONTROL_3]                                            = 0xD0D3,
	[SERDES_TX_PI_TXPICONTROL_5]                                           = 0xD0A5,
	[SERDES_TX_PI_TXPICONTROL_0]                                           = 0xD0A0,
	[SERDES_RX_MISC_CONFIG]                                                = 0xD163,
	[SERDES_TLB_TX_TLB_TX_PAM4_CONFIG_0]                                   = 0xD175,
	[SERDES_RX_CKRST_CTRL_RX_CLOCK_N_RESET_DEBUG_CONTROL]                  = 0xD1A7,
	[SERDES_RX_CKRST_CTRL_RX_LANE_CLK_RESET_N_POWERDOWN_CONTROL]           = 0xD1A1,
	[SERDES_LINKTRN_IEEE_TX_LINKTRNIT_BASE_R_PMD_CONTROL]                  = 0x0096,
	[SERDES_LINKTRN_IEEE_TX_LINKTRNIT_BASE_R_PMD_STATUS]                   = 0x0097,
	[SERDES_TLB_RX_DIG_LPBK_CONFIG]                                        = 0xD162,
	[SERDES_TX_CKRST_CTRL_TX_CLOCK_N_RESET_DEBUG_CONTROL]                  = 0xD1B7,
	[SERDES_TX_CKRST_CTRL_TX_LANE_CLK_RESET_N_POWERDOWN_CONTROL]           = 0xD1B1,
	[SERDES_TX_FED_TXFIR_MISC_CONTROL0]                                    = 0xD131,
	[SERDES_TLB_TX_TXMISC_CONFIG]                                          = 0xD173,
	[SERDES_TLB_TX_RMT_LPBK_CONFIG]                                        = 0xD172,
	[SERDES_TLB_TX_PRBS_GEN_CONFIG]                                        = 0xD171,
	[SERDES_TLB_TX_PATT_GEN_CONFIG]                                        = 0xD170,
	[SERDES_TLB_RX_PRBS_CHK_CONFIG]                                        = 0xD161,
	[SERDES_MICRO_A_COM_AHB_RDADDR_MSW]                                    = 0xD209,
	[SERDES_MICRO_A_COM_AHB_RDADDR_LSW]                                    = 0xD208,
	[SERDES_MICRO_A_COM_AHB_RDDATA_LSW]                                    = 0xD20A,
};

#endif /* _SL_CORE_HW_SERDES_OSPREY_H_ */
