#
# Slingshot link driver
#

obj-m := $(SL_NAME).o

$(SL_NAME)-y := sl_module.o

## FIXME: remove this when "test" is removed
$(SL_NAME)-$(SL_TEST) += \
	sl_test.o                     \
	ctl/test/sl_ctl_test.o        \
	ctl/test/sl_ctl_test_fec.o    \
	ctl/test/sl_ctl_test_ldev.o   \
	ctl/test/sl_ctl_test_lgrp.o   \
	core/test/sl_core_test.o      \
	core/test/sl_core_test_an.o   \
	core/hw/sl_core_hw_fec_test.o \
	core/test/sl_core_test_fec.o  \
	media/test/sl_media_test.o

$(SL_NAME)-$(SL_BUILD_SWITCH) += \
	switch/sl_media.o                           \
	media/switch/sl_media_io.o                  \
	media/switch/sl_media_jack.o                \
	media/data/switch/sl_media_data_jack.o      \
	media/data/switch/sl_media_data_jack_emu.o  \
	core/hw/switch/sl_core_hw_fec.o             \
	core/hw/switch/sl_core_hw_llr.o             \
	core/hw/switch/sl_core_hw_an.o              \
	core/hw/switch/sl_core_hw_mac.o             \
	core/data/switch/sl_core_data_link.o        \
	core/data/switch/sl_core_data_mac.o

$(SL_NAME)-$(SL_BUILD_SWITCH_EMU) += \
	switch/sl_media.o                           \
	media/emu/sl_media_io.o                     \
	media/switch/sl_media_jack.o                \
	media/data/emu/sl_media_data_jack.o         \
	media/data/switch/sl_media_data_jack_emu.o  \
	media/data/nic2/sl_media_data_jack_emu.o    \
	core/hw/switch/sl_core_hw_fec.o             \
	core/hw/switch/sl_core_hw_llr.o             \
	core/hw/switch/sl_core_hw_an.o              \
	core/hw/switch/sl_core_hw_mac.o             \
	core/data/switch/sl_core_data_link.o        \
	core/data/switch/sl_core_data_mac.o

$(SL_NAME)-$(SL_BUILD_NIC2) += \
	nic2/sl_ldev.o                              \
	nic2/sl_media.o                             \
	media/nic2/sl_media_io.o                    \
	media/nic2/sl_media_jack.o                  \
	media/nic2/sl_media_ldev.o                  \
	media/data/nic2/sl_media_data_ldev.o        \
	media/data/nic2/sl_media_data_jack.o        \
	media/data/nic2/sl_media_data_jack_emu.o    \
	core/hw/nic2/sl_core_hw_fec.o               \
	core/hw/nic2/sl_core_hw_llr.o               \
	core/hw/nic2/sl_core_hw_an.o                \
	core/hw/nic2/sl_core_hw_mac.o               \
	core/data/nic2/sl_core_data_link.o          \
	core/data/nic2/sl_core_data_mac.o

$(SL_NAME)-y += \
	sl_ldev.o  \
	sl_lgrp.o  \
	sl_link.o  \
	sl_llr.o   \
	sl_mac.o   \
	sl_media.o \
	sl_fec.o

$(SL_NAME)-y += \
	media/sl_media_lgrp.o                   \
	media/sl_media_ldev.o                   \
	media/sl_media_jack.o                   \
	media/data/sl_media_data_ldev.o         \
	media/data/sl_media_data_lgrp.o         \
	media/data/sl_media_data_jack.o         \
	media/data/sl_media_data_cable_db_ops.o \
	media/base/sl_media_eeprom.o

$(SL_NAME)-y += \
	core/sl_core_ldev.o                 \
	core/sl_core_lgrp.o                 \
	core/sl_core_link.o                 \
	core/sl_core_link_an.o              \
	core/sl_core_link_fec.o             \
	core/sl_core_mac.o                  \
	core/sl_core_llr.o                  \
	core/sl_core_str.o                  \
	core/base/sl_core_timer_link.o      \
	core/base/sl_core_timer_llr.o       \
	core/data/sl_core_data_ldev.o       \
	core/data/sl_core_data_lgrp.o       \
	core/data/sl_core_data_link.o       \
	core/data/sl_core_data_llr.o        \
	core/data/sl_core_data_mac.o        \
	core/hw/sl_core_hw_intr.o           \
	core/hw/sl_core_hw_intr_llr.o       \
	core/hw/sl_core_hw_sbus.o           \
	core/hw/sl_core_hw_pmi.o            \
	core/hw/sl_core_hw_sbus_pmi.o       \
	core/hw/sl_core_hw_uc_ram.o         \
	core/hw/sl_core_hw_serdes.o         \
	core/hw/sl_core_hw_serdes_fw.o      \
	core/hw/sl_core_hw_serdes_core.o    \
	core/hw/sl_core_hw_serdes_link.o    \
	core/hw/sl_core_hw_serdes_lane.o    \
	core/hw/sl_core_hw_serdes_lane_tx.o \
	core/hw/sl_core_hw_serdes_lane_rx.o \
	core/hw/sl_core_hw_link.o           \
	core/hw/sl_core_hw_an.o             \
	core/hw/sl_core_hw_an_lp.o          \
	core/hw/sl_core_hw_an_up.o          \
	core/hw/sl_core_hw_pcs.o            \
	core/hw/sl_core_hw_mac.o            \
	core/hw/sl_core_hw_llr.o            \
	core/hw/sl_core_hw_reset.o          \
	core/test/sl_core_test_serdes.o

$(SL_NAME)-y += \
	ctl/sl_ctl_ldev.o          \
	ctl/sl_ctl_lgrp.o          \
	ctl/sl_ctl_lgrp_notif.o    \
	ctl/sl_ctl_link.o          \
	ctl/sl_ctl_link_priv.o     \
	ctl/sl_ctl_link_fec.o      \
	ctl/sl_ctl_link_fec_priv.o \
	ctl/sl_ctl_link_counters.o \
	ctl/sl_ctl_mac.o           \
	ctl/sl_ctl_llr.o

$(SL_NAME)-y += \
	log/sl_log.o

$(SL_NAME)-y += \
	test/sl_test_common.o

$(SL_NAME)-y += \
	sysfs/sl_sysfs_ldev.o               \
	sysfs/sl_sysfs_lgrp.o               \
	sysfs/sl_sysfs_lgrp_policy.o        \
	sysfs/sl_sysfs_lgrp_config.o        \
	sysfs/sl_sysfs_link.o               \
	sysfs/sl_sysfs_link_policy.o        \
	sysfs/sl_sysfs_link_fec_mon_check.o \
	sysfs/sl_sysfs_link_fec_up_check.o  \
	sysfs/sl_sysfs_link_config.o        \
	sysfs/sl_sysfs_link_degrade.o       \
	sysfs/sl_sysfs_link_caps.o          \
	sysfs/sl_sysfs_link_fec.o           \
	sysfs/sl_sysfs_link_fec_current.o   \
	sysfs/sl_sysfs_link_fec_up.o        \
	sysfs/sl_sysfs_link_fec_down.o      \
	sysfs/sl_sysfs_serdes.o             \
	sysfs/sl_sysfs_serdes_settings.o    \
	sysfs/sl_sysfs_serdes_eye.o         \
	sysfs/sl_sysfs_serdes_state.o       \
	sysfs/sl_sysfs_serdes_swizzle.o     \
	sysfs/sl_sysfs_llr.o                \
	sysfs/sl_sysfs_llr_config.o         \
	sysfs/sl_sysfs_llr_policy.o         \
	sysfs/sl_sysfs_llr_loop_time.o      \
	sysfs/sl_sysfs_mac.o                \
	sysfs/sl_sysfs_media.o              \
	sysfs/sl_sysfs_link_counters.o

ccflags-y := -I$(M)
ccflags-$(SL_BUILD_NIC2) += \
	-I$(M)/nic2         \
	-I$(M)/core/hw/nic2
ccflags-$(SL_BUILD_SWITCH) += \
	-I$(M)/switch         \
	-I$(M)/core/hw/switch
ccflags-$(SL_BUILD_SWITCH_EMU) += \
	-I$(M)/switch             \
	-I$(M)/core/hw/switch
